apiVersion: v1
kind: Namespace
metadata:
  name: custom-metrics
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: custom-metrics-stackdriver-adapter
  namespace: custom-metrics
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: custom-metrics:system:auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: custom-metrics-stackdriver-adapter
  namespace: custom-metrics
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: custom-metrics-auth-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: custom-metrics-stackdriver-adapter
  namespace: custom-metrics
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: custom-metrics-resource-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: custom-metrics-stackdriver-adapter
  namespace: custom-metrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-metrics-stackdriver-adapter
  namespace: custom-metrics
  labels:
    run: custom-metrics-stackdriver-adapter
    k8s-app: custom-metrics-stackdriver-adapter
spec:
  replicas: 1
  selector:
    matchLabels:
      run: custom-metrics-stackdriver-adapter
      k8s-app: custom-metrics-stackdriver-adapter
  template:
    metadata:
      labels:
        run: custom-metrics-stackdriver-adapter
        k8s-app: custom-metrics-stackdriver-adapter
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccountName: custom-metrics-stackdriver-adapter
      containers:
      - image: gcr.io/gke-release/custom-metrics-stackdriver-adapter:v0.15.2-gke.1
        imagePullPolicy: Always
        name: pod-custom-metrics-stackdriver-adapter
        command:
        - /adapter
        - --use-new-resource-model=false
        resources:
          limits:
            cpu: 250m
            memory: 200Mi
          requests:
            cpu: 250m
            memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: custom-metrics-stackdriver-adapter
    k8s-app: custom-metrics-stackdriver-adapter
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: Adapter
  name: custom-metrics-stackdriver-adapter
  namespace: custom-metrics
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    run: custom-metrics-stackdriver-adapter
    k8s-app: custom-metrics-stackdriver-adapter
  type: ClusterIP
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.custom.metrics.k8s.io
spec:
  insecureSkipTLSVerify: false
  caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVMVENDQXBXZ0F3SUJBZ0lSQUlsOHVFUFZDM3hFSkNsVU45S01IRE13RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa1ptTXdaVFZrTlRZdE5HRXpNaTAwWTJOakxUZ3dZMlF0Tm1ZNU1tWmpOV0ptTm1GaApNQ0FYRFRJMU1ESXdNakU1TURjek5Gb1lEekl3TlRVd01USTJNakF3TnpNMFdqQXZNUzB3S3dZRFZRUURFeVJtCll6QmxOV1ExTmkwMFlUTXlMVFJqWTJNdE9EQmpaQzAyWmpreVptTTFZbVkyWVdFd2dnR2lNQTBHQ1NxR1NJYjMKRFFFQkFRVUFBNElCandBd2dnR0tBb0lCZ1FDaXQvTzFOeVFQN09FYnNiRFpoZUFmcUxYZk02TnN6Z3lPUm93WQpIVEV0dEF1cFJlVFJDS1NQa2hlaTJ2RGxnRU5NZHVma3dWeHFlcGNBRldQdWNObHdjSHB1alhJcmNVUHpxSmdWCjU2dW5uUUhNQnBLRHZWQmIrc21ad2RucjhSU2RubE5LRVpTVTZQQkZlTG5RcWYraWdKMGxMeDVQL1hFSkI2VUcKb3Nid0dPaTdlc2FPaGVIcytxSktzSDJGSndaNWx2SXpBOHBwZ0tOZEdoanIwRzI4MFdUa3g1cC8rWEhjeXNhSwpzV0lRZDNMZGpBTXArZHE2dkpaczNaUWdmT2VzZkh4di84eUdRYmdpcy9lL3hKRmgwTC85UFdlTFdqN0NYTVR2CnE5dGNtRkdKNVVrbHBTNWt3aDIrYStKTkM0N2VLcDlZbTd6ZHI2aThyQkZFcENmWUpBclovdTRhSjFOcmszVzAKdFBMVVBqVHFxVnZibHVLUEdkR1ppaVA1Z3l2Yngzd0VEYlBHYXF1WkxDZ2FjbWRjeDBnd3M4NGtnTkhrRnIzeQp1WXBYayt0MCtXczJvMzlRSjgyRWZ3dWVVWkV1RUdoWVVmMlhVL2xhWVYrSnpTWVRZdGVTbUViN1B5RjNYdVZlCmhaM3l4eVl0ajROd3ZDV3ZyVTJqak9pS0Jia0NBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdJRU1BOEcKQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGUHA2VmFZeTlMdVBZWWtKUjFTbzlQZGpkaDBETUEwRwpDU3FHU0liM0RRRUJDd1VBQTRJQmdRQlVYcVBQN1o1NlRVTmRyV3FUZVV5RHBERVZsRjZTS2wzSUVNalFkOTNBCjZvNE51QU14WXFLL2EvdlU5Y0pHamtsaE1TcVhIY3Z5TC9EU2NTc2JwWjc1WjlVT1Q3VDFGc0Y4NDkwem11ekIKaUlsYUEzc0swU1BydjJCYlh6YmZzQUdYdytEWWpNN3FNK3hzeXZqSERRSVN6M1grYjdRbXNNWGJSVG01UVJWRQo1NTk1clJDanB2Z3VzNjQvY09kRGRaQ3RmdmJBVlZRSlJCRkhzdW9FNTd3ZVIrUHZBdGpvWVpETGU2NWpyR0w1Cm1zV1lubTVvcE85dDF5RWRnWmxDbHJqc1E3NDFIVmxRRXZEOU1nN2xTMjlGMFNaVkM0U3hXSVUzL0MwQU5PQlUKY3pWWmhDSUdEVXpMWTdwK2hXMEpOSWZGRmlmamp0aEt5SHpkWDQzTy9OZ0NwRXBqaHY0TkJPN21iTThZaDcrcwozNHE1Z0g1WWlWTnloU3lzdFBPZTBKbGlGQTk5TFFwZnpxeThVLzhZVjBWbml6QW5aMS9mZ080VGE4YzhXT1VIClRGVFBFaW9sUDQydVEyT0VNMjZ3alYrZ2UzaTFJQWd1QjVMRXlGL0tadVJmRXFERlo3SzdDcnVhVlR6SUlRb2YKS1dzTnZGNCtwSU9VQUxJVWZNR0kyaGs9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
  group: custom.metrics.k8s.io
  groupPriorityMinimum: 100
  versionPriority: 100
  service:
    name: custom-metrics-stackdriver-adapter
    namespace: custom-metrics
  version: v1beta1
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta2.custom.metrics.k8s.io
spec:
  insecureSkipTLSVerify: false
  caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVMVENDQXBXZ0F3SUJBZ0lSQUlsOHVFUFZDM3hFSkNsVU45S01IRE13RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa1ptTXdaVFZrTlRZdE5HRXpNaTAwWTJOakxUZ3dZMlF0Tm1ZNU1tWmpOV0ptTm1GaApNQ0FYRFRJMU1ESXdNakU1TURjek5Gb1lEekl3TlRVd01USTJNakF3TnpNMFdqQXZNUzB3S3dZRFZRUURFeVJtCll6QmxOV1ExTmkwMFlUTXlMVFJqWTJNdE9EQmpaQzAyWmpreVptTTFZbVkyWVdFd2dnR2lNQTBHQ1NxR1NJYjMKRFFFQkFRVUFBNElCandBd2dnR0tBb0lCZ1FDaXQvTzFOeVFQN09FYnNiRFpoZUFmcUxYZk02TnN6Z3lPUm93WQpIVEV0dEF1cFJlVFJDS1NQa2hlaTJ2RGxnRU5NZHVma3dWeHFlcGNBRldQdWNObHdjSHB1alhJcmNVUHpxSmdWCjU2dW5uUUhNQnBLRHZWQmIrc21ad2RucjhSU2RubE5LRVpTVTZQQkZlTG5RcWYraWdKMGxMeDVQL1hFSkI2VUcKb3Nid0dPaTdlc2FPaGVIcytxSktzSDJGSndaNWx2SXpBOHBwZ0tOZEdoanIwRzI4MFdUa3g1cC8rWEhjeXNhSwpzV0lRZDNMZGpBTXArZHE2dkpaczNaUWdmT2VzZkh4di84eUdRYmdpcy9lL3hKRmgwTC85UFdlTFdqN0NYTVR2CnE5dGNtRkdKNVVrbHBTNWt3aDIrYStKTkM0N2VLcDlZbTd6ZHI2aThyQkZFcENmWUpBclovdTRhSjFOcmszVzAKdFBMVVBqVHFxVnZibHVLUEdkR1ppaVA1Z3l2Yngzd0VEYlBHYXF1WkxDZ2FjbWRjeDBnd3M4NGtnTkhrRnIzeQp1WXBYayt0MCtXczJvMzlRSjgyRWZ3dWVVWkV1RUdoWVVmMlhVL2xhWVYrSnpTWVRZdGVTbUViN1B5RjNYdVZlCmhaM3l4eVl0ajROd3ZDV3ZyVTJqak9pS0Jia0NBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdJRU1BOEcKQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGUHA2VmFZeTlMdVBZWWtKUjFTbzlQZGpkaDBETUEwRwpDU3FHU0liM0RRRUJDd1VBQTRJQmdRQlVYcVBQN1o1NlRVTmRyV3FUZVV5RHBERVZsRjZTS2wzSUVNalFkOTNBCjZvNE51QU14WXFLL2EvdlU5Y0pHamtsaE1TcVhIY3Z5TC9EU2NTc2JwWjc1WjlVT1Q3VDFGc0Y4NDkwem11ekIKaUlsYUEzc0swU1BydjJCYlh6YmZzQUdYdytEWWpNN3FNK3hzeXZqSERRSVN6M1grYjdRbXNNWGJSVG01UVJWRQo1NTk1clJDanB2Z3VzNjQvY09kRGRaQ3RmdmJBVlZRSlJCRkhzdW9FNTd3ZVIrUHZBdGpvWVpETGU2NWpyR0w1Cm1zV1lubTVvcE85dDF5RWRnWmxDbHJqc1E3NDFIVmxRRXZEOU1nN2xTMjlGMFNaVkM0U3hXSVUzL0MwQU5PQlUKY3pWWmhDSUdEVXpMWTdwK2hXMEpOSWZGRmlmamp0aEt5SHpkWDQzTy9OZ0NwRXBqaHY0TkJPN21iTThZaDcrcwozNHE1Z0g1WWlWTnloU3lzdFBPZTBKbGlGQTk5TFFwZnpxeThVLzhZVjBWbml6QW5aMS9mZ080VGE4YzhXT1VIClRGVFBFaW9sUDQydVEyT0VNMjZ3alYrZ2UzaTFJQWd1QjVMRXlGL0tadVJmRXFERlo3SzdDcnVhVlR6SUlRb2YKS1dzTnZGNCtwSU9VQUxJVWZNR0kyaGs9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
  group: custom.metrics.k8s.io
  groupPriorityMinimum: 100
  versionPriority: 200
  service:
    name: custom-metrics-stackdriver-adapter
    namespace: custom-metrics
  version: v1beta2
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.external.metrics.k8s.io
spec:
  insecureSkipTLSVerify: false
  caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVMVENDQXBXZ0F3SUJBZ0lSQUlsOHVFUFZDM3hFSkNsVU45S01IRE13RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa1ptTXdaVFZrTlRZdE5HRXpNaTAwWTJOakxUZ3dZMlF0Tm1ZNU1tWmpOV0ptTm1GaApNQ0FYRFRJMU1ESXdNakU1TURjek5Gb1lEekl3TlRVd01USTJNakF3TnpNMFdqQXZNUzB3S3dZRFZRUURFeVJtCll6QmxOV1ExTmkwMFlUTXlMVFJqWTJNdE9EQmpaQzAyWmpreVptTTFZbVkyWVdFd2dnR2lNQTBHQ1NxR1NJYjMKRFFFQkFRVUFBNElCandBd2dnR0tBb0lCZ1FDaXQvTzFOeVFQN09FYnNiRFpoZUFmcUxYZk02TnN6Z3lPUm93WQpIVEV0dEF1cFJlVFJDS1NQa2hlaTJ2RGxnRU5NZHVma3dWeHFlcGNBRldQdWNObHdjSHB1alhJcmNVUHpxSmdWCjU2dW5uUUhNQnBLRHZWQmIrc21ad2RucjhSU2RubE5LRVpTVTZQQkZlTG5RcWYraWdKMGxMeDVQL1hFSkI2VUcKb3Nid0dPaTdlc2FPaGVIcytxSktzSDJGSndaNWx2SXpBOHBwZ0tOZEdoanIwRzI4MFdUa3g1cC8rWEhjeXNhSwpzV0lRZDNMZGpBTXArZHE2dkpaczNaUWdmT2VzZkh4di84eUdRYmdpcy9lL3hKRmgwTC85UFdlTFdqN0NYTVR2CnE5dGNtRkdKNVVrbHBTNWt3aDIrYStKTkM0N2VLcDlZbTd6ZHI2aThyQkZFcENmWUpBclovdTRhSjFOcmszVzAKdFBMVVBqVHFxVnZibHVLUEdkR1ppaVA1Z3l2Yngzd0VEYlBHYXF1WkxDZ2FjbWRjeDBnd3M4NGtnTkhrRnIzeQp1WXBYayt0MCtXczJvMzlRSjgyRWZ3dWVVWkV1RUdoWVVmMlhVL2xhWVYrSnpTWVRZdGVTbUViN1B5RjNYdVZlCmhaM3l4eVl0ajROd3ZDV3ZyVTJqak9pS0Jia0NBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdJRU1BOEcKQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGUHA2VmFZeTlMdVBZWWtKUjFTbzlQZGpkaDBETUEwRwpDU3FHU0liM0RRRUJDd1VBQTRJQmdRQlVYcVBQN1o1NlRVTmRyV3FUZVV5RHBERVZsRjZTS2wzSUVNalFkOTNBCjZvNE51QU14WXFLL2EvdlU5Y0pHamtsaE1TcVhIY3Z5TC9EU2NTc2JwWjc1WjlVT1Q3VDFGc0Y4NDkwem11ekIKaUlsYUEzc0swU1BydjJCYlh6YmZzQUdYdytEWWpNN3FNK3hzeXZqSERRSVN6M1grYjdRbXNNWGJSVG01UVJWRQo1NTk1clJDanB2Z3VzNjQvY09kRGRaQ3RmdmJBVlZRSlJCRkhzdW9FNTd3ZVIrUHZBdGpvWVpETGU2NWpyR0w1Cm1zV1lubTVvcE85dDF5RWRnWmxDbHJqc1E3NDFIVmxRRXZEOU1nN2xTMjlGMFNaVkM0U3hXSVUzL0MwQU5PQlUKY3pWWmhDSUdEVXpMWTdwK2hXMEpOSWZGRmlmamp0aEt5SHpkWDQzTy9OZ0NwRXBqaHY0TkJPN21iTThZaDcrcwozNHE1Z0g1WWlWTnloU3lzdFBPZTBKbGlGQTk5TFFwZnpxeThVLzhZVjBWbml6QW5aMS9mZ080VGE4YzhXT1VIClRGVFBFaW9sUDQydVEyT0VNMjZ3alYrZ2UzaTFJQWd1QjVMRXlGL0tadVJmRXFERlo3SzdDcnVhVlR6SUlRb2YKS1dzTnZGNCtwSU9VQUxJVWZNR0kyaGs9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
  group: external.metrics.k8s.io
  groupPriorityMinimum: 100
  versionPriority: 100
  service:
    name: custom-metrics-stackdriver-adapter
    namespace: custom-metrics
  version: v1beta1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-metrics-reader
rules:
- apiGroups:
  - "external.metrics.k8s.io"
  resources:
  - "*"
  verbs:
  - list
  - get
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-metrics-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-metrics-reader
subjects:
- kind: ServiceAccount
  name: horizontal-pod-autoscaler
  namespace: kube-system
