apiVersion: v1
kind: ConfigMap
metadata:
  name: skeletoncache-config-v${SKELETONCACHE_CONFIG_VERSION}
  namespace: default
data:
  config.cfg: |
    SKELETON_CACHE_BUCKET = "gs://${SKELETON_CACHE_BUCKET}"
    SKELETONCACHE_MAX_REPLICAS = ${SKELETONCACHE_MAX_REPLICAS}
---
apiVersion: v1
kind: Service
metadata:
  name: skeletoncache-service
spec:
  type: NodePort
  selector:
    app: skeletoncache
  ports:
    - port: 80
      targetPort: 80
---
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: skeletoncache-scaler
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: skeletoncache
#   minReplicas: ${SKELETONCACHE_MIN_REPLICAS}
#   maxReplicas: ${SKELETONCACHE_MAX_REPLICAS}
#   metrics:
#     - type: Resource
#       resource:
#         name: cpu
#         target:
#           type: Utilization
#           averageUtilization: 90
#     - type: Pods
#       pods:
#         metric:
#           name: custom.googleapis.com|http|uwsgi_perc_busy_workers
#         target:
#           type: AverageValue
#           averageValue: 75
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: keda-skeletoncache-scaler
  namespace: default
  # annotations:
  #   scaledobject.keda.sh/transfer-hpa-ownership: "true"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: skeletoncache
  pollingInterval: 15
  cooldownPeriod: 300
  minReplicaCount: ${SKELETONCACHE_MIN_REPLICAS}
  maxReplicaCount: ${SKELETONCACHE_MAX_REPLICAS}
  triggers:
    - type: cpu
      metricType: Utilization # Allowed types are 'Utilization' or 'AverageValue'
      metadata:
        value: "75"
        # containerName: "" # Optional. You can use this to target a specific container in a pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skeletoncache
spec:
  selector:
    matchLabels:
      app: skeletoncache
  template:
    metadata:
      labels:
        app: skeletoncache
    spec:
      tolerations:
        - key: "pool"
          operator: "Equal"
          value: "${MESH_POOL}"
          effect: "NoSchedule"
      nodeSelector:
        cloud.google.com/gke-nodepool: ${MESH_POOL}
      volumes:
        - name: google-cloud-key
          secret:
            secretName: ${SKELETON_SERVICE_ACCOUNT_SECRET}
        - name: skeleton-config-volume
          configMap:
            name: skeletoncache-config-v${SKELETONCACHE_CONFIG_VERSION}
      terminationGracePeriodSeconds: 10
      containers:
        - name: skeletoncache
          image: ${DOCKER_REPOSITORY}/skeletoncache:v${SKELETONCACHE_VERSION}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: google-cloud-key
              mountPath: /home/nginx/.cloudvolume/secrets
            - name: skeleton-config-volume
              mountPath: /app/skeletoncache/app/instance/
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /home/nginx/.cloudvolume/secrets/${GOOGLE_SECRET_FILENAME}
            - name: GOOGLE_APPLICATION_CREDENTIALS_FILE
              valueFrom:
                secretKeyRef:
                  name: ${PYCG_SERVICE_ACCOUNT_SECRET}
                  key: ${GOOGLE_SECRET_FILENAME}
            - name: GLOBAL_SERVER_URL
              value: https://${GLOBAL_SERVER}
            - name: AUTH_URI
              value: ${AUTH_URI}
            - name: STICKY_AUTH_URL
              value: ${STICKY_AUTH_URL}
            - name: AUTH_URL
              value: ${AUTH_URL}
            - name: INFO_URL
              value: ${INFO_URL}
            - name: PROJECT_NAME
              value: ${PROJECT_NAME}
            - name: SKELETONSERVICE_SETTINGS
              value: "/app/skeletoncache/app/instance/config.cfg"
            - name: APP_SETTINGS
              value: "skeletoncache.app.config.DevelopmentConfig"
            - name: DAF_CREDENTIALS
              value: /home/nginx/.cloudvolume/secrets/${CAVE_SECRET_FILENAME}
            - name: SKELETON_CACHE_LOW_PRIORITY_EXCHANGE
              value: ${SKELETON_CACHE_LOW_PRIORITY_EXCHANGE}
            - name: SKELETON_CACHE_HIGH_PRIORITY_EXCHANGE
              value: ${SKELETON_CACHE_HIGH_PRIORITY_EXCHANGE}
            - name: SKELETON_CACHE_LOW_PRIORITY_RETRIEVE_QUEUE
              value: ${SKELETON_CACHE_LOW_PRIORITY_RETRIEVE_QUEUE}
            - name: SKELETON_CACHE_HIGH_PRIORITY_RETRIEVE_QUEUE
              value: ${SKELETON_CACHE_HIGH_PRIORITY_RETRIEVE_QUEUE}
          resources:
            requests:
              memory: 600Mi
              cpu: 50m
          readinessProbe:
            httpGet:
              path: /skeletoncache/health
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 60
          livenessProbe:
            httpGet:
              path: /skeletoncache/health
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 60
        # - name: uwsgi-exporter
        #   image: caveconnectome/uwsgi-export-workers:v14
        #   # Exposes the metrics endpoint on 0.0.0.0:9101
        #   ports:
        #      - containerPort: 9101
        #   env:
        #   # This tells the exporter where to find the uWSGI stats server
        #   - name: UWSGI_STATS_URL
        #     value: "http://localhost:1717"
        #   readinessProbe:
        #     httpGet:
        #       path: /
        #       port: 8080
        #     initialDelaySeconds: 5
        #     periodSeconds: 5
        # - name: prometheus-to-sd
        #   image: gcr.io/google-containers/prometheus-to-sd:v0.8.0
        #   command: ["/monitor"]
        #   args:
        #     - --source=http://localhost:9101/metrics
        #     - --stackdriver-prefix=custom.googleapis.com
        #     - --pod-id=$(POD_ID)
        #     - --namespace-id=$(POD_NAMESPACE)
        #   env:
        #     # save Kubernetes metadata as environment variables for use in metrics
        #     - name: POD_ID
        #       valueFrom:
        #         fieldRef:
        #           fieldPath: metadata.uid
        #     - name: POD_NAME
        #       valueFrom:
        #         fieldRef:
        #           fieldPath: metadata.name
        #     - name: POD_NAMESPACE
        #       valueFrom:
        #         fieldRef:
        #           fieldPath: metadata.namespace
        - name: sysctl-buddy
          image: alpine:3.4
          command:
            - /bin/sh
            - -c
            - |
              while true; do
                sysctl -w net.core.somaxconn=32768
                sysctl -w net.ipv4.ip_local_port_range='1024 65535'
                sleep 100
              done
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          resources:
            requests:
              memory: 10Mi
              cpu: 5m
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: keda-skeletoncache-worker-scaler
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: skeletoncache-worker
  pollingInterval:  15
  cooldownPeriod:  300
  idleReplicaCount: 1                                       
  minReplicaCount: ${SKELETONCACHE_WORKER_MIN_REPLICAS} 
  maxReplicaCount: ${SKELETONCACHE_WORKER_MAX_REPLICAS}
  triggers:
  - type: gcp-pubsub
    metadata:
      mode: "SubscriptionSize"
      value: "10" # Optional - Default is 10
      activationValue: "0" # Optional - Default is 0
      subscriptionName: ${SKELETON_CACHE_LOW_PRIORITY_RETRIEVE_QUEUE}
      credentialsFromEnv: GOOGLE_APPLICATION_CREDENTIALS_FILE  # Required
  - type: gcp-pubsub
    metadata:
      mode: "SubscriptionSize"
      value: "5" # Optional - Default is 10
      activationValue: "0" # Optional - Default is 0
      subscriptionName: ${SKELETON_CACHE_HIGH_PRIORITY_RETRIEVE_QUEUE}
      credentialsFromEnv: GOOGLE_APPLICATION_CREDENTIALS_FILE  # Required
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skeletoncache-worker
spec:
  selector:
    matchLabels:
      app: skeletoncache-worker
  template:
    metadata:
      labels:
        app: skeletoncache-worker
    spec:
      tolerations:
        - key: "pool"
          operator: "Equal"
          value: "${MESH_POOL}"
          effect: "NoSchedule"
      nodeSelector:
        cloud.google.com/gke-nodepool: ${MESH_POOL}
      volumes:
        - name: google-cloud-key
          secret:
            secretName: ${SKELETON_SERVICE_ACCOUNT_SECRET}
        - name: sksv-config-volume
          configMap:
            name: skeletoncache-config-v${SKELETONCACHE_CONFIG_VERSION}
      terminationGracePeriodSeconds: 10
      containers:
        - name: skeletoncache-worker
          image: ${DOCKER_REPOSITORY}/skeletoncache:v${SKELETONCACHE_VERSION}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: google-cloud-key
              mountPath: /root/.cloudvolume/secrets
            - name: sksv-config-volume
              mountPath: /app/skeletoncache/app/instance/
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /root/.cloudvolume/secrets/${GOOGLE_SECRET_FILENAME}
            - name: GOOGLE_APPLICATION_CREDENTIALS_FILE
              valueFrom:
                secretKeyRef:
                  name: ${PYCG_SERVICE_ACCOUNT_SECRET}
                  key: ${GOOGLE_SECRET_FILENAME}
            - name: GLOBAL_SERVER_URL
              value: https://${GLOBAL_SERVER}
            - name: AUTH_URI
              value: ${AUTH_URI}
            - name: STICKY_AUTH_URL
              value: ${STICKY_AUTH_URL}
            - name: BIGTABLE_PROJECT
              value: ${DATA_PROJECT_NAME}
            - name: BIGTABLE_INSTANCE
              value: ${BIGTABLE_INSTANCE_NAME}
            - name: AUTH_URL
              value: ${AUTH_URL}
            - name: INFO_URL
              value: ${INFO_URL}
            - name: APP_SETTINGS
              value: "skeletoncache.app.config.DevelopmentConfig"
            - name: SKELETON_CACHE_URL_PREFIX
              value: sksv
            - name: PROJECT_ID
              value: ${DATA_PROJECT_NAME}
            - name: PROJECT_NAME
              value: ${PROJECT_NAME}
            - name: SKELETON_CACHE_LOW_PRIORITY_EXCHANGE
              value: ${SKELETON_CACHE_LOW_PRIORITY_EXCHANGE}
            - name: SKELETON_CACHE_HIGH_PRIORITY_EXCHANGE
              value: ${SKELETON_CACHE_HIGH_PRIORITY_EXCHANGE}
            - name: SKELETON_CACHE_LOW_PRIORITY_RETRIEVE_QUEUE
              value: ${SKELETON_CACHE_LOW_PRIORITY_RETRIEVE_QUEUE}
            - name: SKELETON_CACHE_HIGH_PRIORITY_RETRIEVE_QUEUE
              value: ${SKELETON_CACHE_HIGH_PRIORITY_RETRIEVE_QUEUE}
            - name: AUTH_USE_REDIS
              value: "false"
            - name: DAF_CREDENTIALS
              value: /root/.cloudvolume/secrets/${CAVE_SECRET_FILENAME}
          resources:
            requests:
              memory: 2500Mi
              cpu: 250m
          command:
            - /bin/sh
            - -c
            - python -u -m skeletonservice.datasets.messaging

            